package(default_visibility = ["//visibility:public"])

load("@org_tensorflow_tensorboard//tensorboard/defs:web.bzl", "tf_web_library")

tf_web_library(
	name = "util",
	srcs = [
		"util.html",
		"util.ts"
	],
	path = "/util"
)
