package(default_visibility = ["//visibility:public"])

load("@org_tensorflow_tensorboard//tensorboard/defs:web.bzl", "tf_web_library")

tf_web_library(
	name = "palette",
	srcs = [
		"palette.js",
		"palette.html"
	],
	path = "/libraries/palette"
)
