alias(
  name = "inception_v3",
  actual = "@model_inception_v3//:inception-v3/model.ckpt-157585",
  visibility = ["//advis_plugin:__pkg__"]
)

exports_files(
  ["inception-v3/model.ckpt-157585"],
  visibility = ["//visibility:public"]
)
